Implement password strength validation (CR-001)
//github.com/melat-mekonnen/todo-scm-project
 * branch            feature-login -> FETCH_HEAD
CONFLICT (modify/delete): src/login.html deleted in HEAD and modified in 1c35142 (Implement password strength validation (CR-001)).  Version 1c35142 (Implement password strength validation (CR-001)) of src/login.html left in tree.
CONFLICT (modify/delete): src/script.js deleted in HEAD and modified in 1c35142 (Implement password strength validation (CR-001)).  Version 1c35142 (Implement password strength validation (CR-001)) of src/script.js left in tree.
error: could not apply 1c35142... Implement password strength validation (CR-001)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
.git/COMMIT_EDITMSG [unix] (16:15 24/12/2025)                        22,1 Bot
Type  :qa  and press <Enter> to exit Vim                             #